
  - name: Change the hostname
    hostname:
      name: "{{ hostname }}"

  - name: Check docker
    command: docker --version
    register: docker_exists
    ignore_errors: yes

  - name: Get docker sh
    get_url:
      url: https://get.docker.com/
      dest: /tmp/get-docker.sh

  - name: Give execute permission
    file:
      path: /tmp/get-docker.sh
      owner: root
      group: root
      mode: '1777'
    

  - name: Run script
    shell: bash /tmp/get-docker.sh
    when: docker_exists.failed

  - name: Enable docker
    systemd: 
      state: started
      name: docker

  - name: Create minio data dir
    file:
      path: /minio/data
      state: directory

  - name: Check minio is running
    shell: docker ps | grep minio
    register: minio_running
    ignore_errors: yes

  - name: Run minio container
    shell: docker run -td -p 9000:9000 -p 9001:9001 --name minio-container -v /minio/data:/data quay.io/minio/minio server /data --console-address ":9001"
    when: minio_running.stdout == ""
